### ISSUE TITLE
Link to Pango lineage

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#138]
Github request: add a hotlink to <https://github.com/cov-lineages/pango-designation/blob/master/lineage_notes.txt> everywhere that it says “Pango lineage”, since I often go there to figure out who is descended from whom quickly. [Very minor, but I’m trying the Slack-&gt;Github posting.]

[Slack Message](https://covarr-net.slack.com/archives/C025AGXG7JT/p1676048232168199)

**Comment by fionabrinkman** [comment]
This is fantastic, though I must say I find it a bit confusing since it doesn't really show recent relationships between lineages. For example, for DN.1 it says:
DN.1	Alias of B.1.1.529.5.3.1.1.1.1.1.1.5.1, S:K147N
so its not clear that is a descendant of BQ.1.1.5 - unless you know to look at BQ.1.1.5 and can see that it is:
BQ.1.1.5	Alias of B.1.1.529.5.3.1.1.1.1.1.1.5, ORF1b:P2313L, ORF1a:V3855I
So, this is great, but it would be wonderful if it would also list what the variant before it is i.e.
DN.1	Descendant of BQ.1.1.5, Alias of B.1.1.529.5.3.1.1.1.1.1.1.5.1, S:K147N
Then you can see the variant growing even when its being mispredicted or the lineage assignments aren't updated yet (such as for DN.1.1.1 right now)
Technically we could build such a table in an automated way, or mention it to them... :)

**Comment by bfjia** [comment]
Where do you find that descendant information?

**Comment by RaphaelRaphael** [comment]
Here is an example of what should be printed automatically 
`DR:	DR is BQ.1.1.3, BQ is BE.1.1.1, BE is BA.5.3.1, BA is B.1.1.529`

Here is a bash oneliner that should generate all the difinitions from the pangolineage file 
`cat data_needed/pango_designation_alias_key_viralai.tsv | grep -v lineage | sort -k2,2 | awk '{actualP=$2;is="";for(i=NR-1;i>0;i--){re="^"p[n[i]]"[^0-9]";if(actualP~re){gsub(p[n[i]],n[i],actualP);is=", "t[n[i]]""is}}n[NR]=$1;p[$1]=$2;t[$1]=$1" is "actualP""is;printf "%s:\t%s\n",$1,t[$1]}'`

**Comment by RaphaelRaphael** [comment]
Update of the one liner : 
`cat data_needed/pango_designation_alias_key.tsv | grep -v lineage | sort -k2,2 | awk '{actualP=$2;is="";for(i=NR-1;i>0;i--){re="^"p[n[i]]"[^0-9A-Z]";if(actualP~re){gsub(p[n[i]],n[i],actualP);is=", "t[n[i]]""is}}n[NR]=$1;p[$1]=$2;t[$1]=$1" is "actualP""is;printf "%s:\t%s\n",$1,t[$1]}'`
