### ISSUE TITLE
Use caching to speed up Rmd knit process during development?

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#170]
Setting `cache=TRUE` will prevent knitr from running a code chunk if it has previously been run and there has been no changes to the code:
https://bookdown.org/yihui/rmarkdown-cookbook/cache.html

**Comment by bfjia** [comment]
I personally set caching as the global default when I'm doing dev so this is a great idea. Rather than adding `cache=T` in each individual chunk, you can set it as the global default using `knitr::opts_chunk$set(cache = TRUE)` at the beginning of the RMD or specify it before the knit command in CLI. 

I dont know how caching behaves across different computers since the cache folder is local so I dont think we should put this as the default behavior.
