### ISSUE TITLE
Possible issue with non-stricto grouping in the fastest growing lineage plot

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#175]
One thing to check: why is the non-stricto plot showing only one other lineage, but the stricto plot has more (I thought that the non stricto plot always contained all of the stricto clades plus additional ones).

[Slack Message](https://covarr-net.slack.com/archives/C025AGXG7JT/p1680468911767249?thread_ts=1680373903.709199&cid=C025AGXG7JT)

**Comment by fionabrinkman** [comment]
Aren't the non-stricto groups though including everything in that non-stricto group, including the stricto lineages showing most growth and those not showing as much growth? So the BQ.1.1 collection of sublineages are mostly petering out or not showing high growth collectively, as expected due to benefit of the 486P mutation in XBB.1.5 and others, whereas the XBB.1.9 sublineages as a group are all showing an advantage, due to the 486P mutation plus an additional mutation and more evolutionary room to adapt now that they have the 486P?
I like doing it this way as it will really reveal when we have *either* sets of lineages all showing growth, or just particular stricto lineages showing growth. Then we can look at the mutations associated with the sets (or individual) lineages further.
Make sense?

**Comment by RaphaelRaphael** [comment]
Yes the non stricto plot show only positive selection estimate and a maximum of 25 non stricto lineages

**Comment by bfjia** [comment]
all good.
