### ISSUE TITLE
Update methods for case-count trends

### ISSUE THREAD

**Issue by spotto** [CoVaRR-NET/duotang#204]
Hi duotang team (and <@U021MMW9NHL>),
I'm using the duotang to train a student on some of the methods in there, and I found the case-count trends section lacking in clarity, particularly for reproducibility or teaching.
e.g. it's missing from the methodology section, that would explain how the R script works but also:
which smooth fitting does it is use (there are several and I don't see the reasoning for when to use which)? what's the shape of the dataframe that the R script needs? what's the equation for r? how does it use s?  etc.
maybe this is written somewhere else and I missed it?
If I didn't we should probably set up an issue for this. Thanks!

[Slack Message](https://covarr-net.slack.com/archives/C020WAJS0DD/p1682965277022999)

**Comment by bfjia** [comment]
The following would be a subheading under the Methodology/Selection Tab, following the Selection Coefficient heading

## Case count trends by variant

Reported cases among people aged over 70 are obtained from the Ontario Data Catalogue (Ontario), BC Center for Disease Control Health Info Database (British Columbia), COVID-19 info for Albertans (Alberta), Centre d'expertise et de référence en santé publique (Quebec), Canada Health InfoBase (Canada). These reported case counts are then normalized to cases per 100,000 individual based off of Statistics Canada's population estimates for each province. We then remove the last 2 datapoints for Canada and last 5 data points for provinces to remove under reported data. This normalized cases over time is then log transformed and then fitted to a smooth spline with a lambda value of 0.001 using the R stats' smooth.spline() function. 

Using the previously discussed methods to estimate selection. A fitted model is made for each lineage of interest that represents the estimated proportion (0-1) of a lineage over time. By multiplying the smooth spline from cases to this lineage frequency model across all time points, we can estimate the inferred number of reported cases over 70 that is due to a specific lineage at a time point.   

Finally, once the inferred counts of each type are calculated, we take the last two days of data from the smooth spline times lineage frequency curve to get n[t] and n[t-1], from which the growth rate of that lineage is estimated as n[t] = n[t-1]*exp(r*1), i.e., r = log(n[t]/n[t-1]) where log is the natural log.
