### ISSUE TITLE
Under reported case counts in Canada

### ISSUE THREAD

**Issue by bfjia** [CoVaRR-NET/duotang#215]
That last point this update looks really low.

**Comment by fionabrinkman** [comment]
Yes, this is something we really need to discuss asap. To address the issue of some provs not really releasing so much data now, for the Canada plot of case counts per variant, I suggest we calculate the number of cases as a per 100K population for the country for ONLY those provinces with recent data (currently BC, Alberta, Ontario and Quebec). If not, the case count for the country looks really low due to some other provs not having much data, even though the per 100K denominator includes population of these provinces not releasing data (correct @bfjia?). Justin and I suspect this is the case, since the plots per prov show no notable dropoff - only the plot for Canada shows a notable drop off.

**Comment by bfjia** [comment]
As per discussion from the duotang tech meeting. This will be kept as is, without dropping the last underreported data point of Canada case count plot
