### ISSUE TITLE
stacked area plots

### ISSUE THREAD

**Issue by ArtPoon** [CoVaRR-NET/duotang#36]
An interactive streamgraph would be a nice replacement for the current stacked barplots of VoC frequencies

**Comment by ArtPoon** [comment]
Potential feature enhancements:
* limit date range (interactively?)
* modify variant set being displayed
* provide as a resource separate from the duotang document, to be automatically updated on a daily or near daily basis

**Comment by fionabrinkman** [comment]
re feature enhancements, these sound great. 

I'm not sure what you mean re the third point about a separate resource though - how often would the duotang be updated, as if that was updated enough would that not be fine? 

A proposal for one graph that could be added (in addition to the existing plots):
- a stacked bar plot, for a rolling range of the past 3 months, of the top 10 subvariants (as currently classified) as a proportion of all cases (ordered by most prevalent variant at the top, to least prevalent on the bottom of the stack, at the most recent date, such that the one that is currently most prevalent is what shows up at the top. Though if you prefer it beig the one most prevalent is at the bottom, that's fine too!). Of course there would need to be disclaimers re how variant classification is always changing, etc. Once the variant classifications are in the database hopefully this would be quite dooable to keep up to date?

**Comment by fionabrinkman** [comment]
Anything more interactive is great. I do find it helpful to look at data over a certain range, depending on what's going on with regard to variants rising and falling.  But in my experience the past 3 months is at least a good start (Hmmm... perhaps that's because of the three month notable waning in immunity - that it translates into this being a useful range?)

**Comment by ArtPoon** [comment]
If our outputs have to be reviewed before release, I don't think it would be feasible to update duotang more frequently than every two weeks, and if it were up to me to lead the development cycle then I wouldn't have the bandwidth to do updates more often than once a month.

What I was trying to get at with making the stacked barplots into a separate resource is that (conditional on lineage classifications being available from the database), it can be completely automated instead of having to go through our manual processing, review and pull request workflow.

**Comment by fionabrinkman** [comment]
Ahhh I see what you mean. I misunderstood the nature of the approval. I thought approval was for any change in what graphs are displayed - NOT approval for each time the data changes. For clarity, I thought there would be regular automated updates of the data displayed that wouldn't require approval - as its just public data and they would be generally agreeing to that level of data being displayed and the way its been displayed and described. Am I wrong and approval would be needed each time the data changes? That seems to put a lot of burden on everyone. 

So, I wonder if approval could be made for just the types of displays (graphs etc) and the wording, so that the data could be updated regularly in an automated fashion to show the latest analysis? Sorry that I fundamentally misunderstood this!

**Comment by ArtPoon** [comment]
Interactive streamgraph now implemented in branch`r2d3`.
I want to add the following additional features before submitting a PR to `dev`:
* [ ] mouseover reports variant (*e.g.*, BA.1) and frequency in week
* [ ] vertical axis / scale bar
* [ ] toggle between national and provincial data sets
* [ ] colour legend

**Comment by ArtPoon** [comment]
I've managed to pass province-specific counts from R to D3 instead of just a single table of nation-wide counts, by customizing the data conversion with a call to `jsonlite::toJSON`:
https://rstudio.github.io/r2d3/articles/data_conversion.html#custom-conversion

For now I modified the JS code so that it just extracts the `Canada` entry from the data received, so everything looks the same.  However, I am now getting a console error that I was not getting before:
```js
Error: <path> attribute d: Expected number, "M0,NaNL1.2882882882…".
```

It seems to be associated with this code block:
```js
var barplot = g.selectAll("path")
                 .data(series)
                 .enter().append("path")
                 .attr("class", "layer")
                 .attr("d", area)
                 .attr("fill", function(d, i) { return color(i); });
```
specifically the call to `.attr("d", area)`

This may be a related thread:
https://stackoverflow.com/questions/35930047/d3-line-chart-x-line-function-always-renders-nan
